//! Real `pallet-revive` storage weight model — the authoritative cost of a
//! contract storage operation on Polkadot Asset Hub Westend.
//!
//! # Why this exists
//!
//! A naive "slot reads per query" counter treats every SLOAD as equal. The
//! real on-chain meter (`pallet-revive`) charges a per-op base weight PLUS a
//! per-byte weight over the value(s) touched, plus a worst-case "full vs empty
//! storage" overhead. A 416-byte B-tree node read costs meaningfully more than
//! a 32-byte scalar read. This module reproduces the exact arithmetic the
//! `pallet-revive` VM gas meter performs, so the OrderedIndex optimization
//! loop minimizes the real on-chain weight — not a proxy that can point the
//! wrong way once per-byte cost is counted.
//!
//! # Source of truth
//!
//! Every constant below is transcribed from the `polkadot-sdk` reference
//! checkout (the `@polkadot-sdk` repo reference), specifically:
//!
//! - `substrate/frame/revive/src/vm/runtime_costs.rs` — the VM gas meter:
//!   `RuntimeCosts::Token::weight()`, the `cost_storage!` macro that routes a
//!   storage op to its `WeightInfo` function AND adds the `(full - empty)`
//!   worst-case overhead. This is the authoritative op -> weight mapping.
//! - `substrate/frame/revive/src/benchmarking.rs` (~line 1518) — confirms
//!   `seal_set_storage(n, o)`: **n = NEW byte size, o = OLD byte size**,
//!   range `[0, 416]`.
//! - `substrate/frame/revive/src/vm/pvm/env.rs` (~line 220) — confirms routing:
//!   `set_storage_or_clear` clears when the 32-byte value is all-zero, else
//!   sets; `get_storage_or_zero` reads a fixed 32 bytes.
//! - `cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_revive.rs`
//!   — autogenerated coefficients (benchmark run dated 2026-05-25).
//! - `cumulus/parachains/runtimes/assets/asset-hub-westend/src/weights/rocksdb_weights.rs`
//!   — `DbWeight`: read = 25_000 ns, write = 100_000 ns (i.e. 25M / 100M ps;
//!   `RuntimeDbWeight` contributes `0` to proof_size).
//!
//! # Derivation
//!
//! Per the `cost_storage!` macro, a storage op's weight is its `WeightInfo`
//! function PLUS a worst-case overhead:
//!
//! ```text
//! cost_storage!(read,  seal_get_storage, n)        = seal_get_storage(n)        + (get_storage_full - get_storage_empty)
//! cost_storage!(write, seal_set_storage, new, old) = seal_set_storage(new, old) + (set_storage_full - set_storage_empty)
//! cost_storage!(write, clear_storage,    old)      = clear_storage(old)         + (set_storage_full - set_storage_empty)
//! ```
//!
//! The `(full - empty)` delta cancels the `DbWeight` term both sides share, so
//! it is a clean constant per op:
//!
//! | term                              | ref_time (ps) | proof (bytes) |
//! |-----------------------------------|---------------|---------------|
//! | `get_storage_full - get_storage_empty` | 32_329_000 | 10_010        |
//! | `set_storage_full - set_storage_empty` | 32_963_000 | 10_010        |
//!
//! Combining each `seal_*`/`clear_storage` base + per-byte + `DbWeight` +
//! overhead yields the closed forms exposed by [`read_weight`],
//! [`write_weight`], [`clear_weight`]:
//!
//! | op             | ref_time (ps)                    | proof (bytes) |
//! |----------------|----------------------------------|---------------|
//! | read `n`       | `69_340_610 + 1561·n`            | `10_262 + n`  |
//! | write `new,old`| `170_975_834 + 423·new + 344·old`| `10_262 + old`|
//! | clear `old`    | `173_290_010 + 958·old`          | `10_262 + old`|
//!
//! `ref_time` is in picoseconds (the unit `frame_benchmarking` emits);
//! `proof_size` is in bytes (the PoV/state-proof size the runtime charges).
//! These are the SAME units polkadot-sdk's generated `Weight` uses.

#![cfg(not(target_arch = "riscv64"))]
// Pure arithmetic over u64 — no allocations, no I/O, no panics on the hot path
// (saturating adds only). Usable from `no_std` if ever needed on-chain.

/// `Weight` as the `pallet-revive` runtime sees it: `ref_time` in picoseconds
/// (compute time) and `proof_size` in bytes (state-proof / PoV size). Both are
/// `u64`; both saturate rather than overflow.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Weight {
    pub ref_time_ps: u64,
    pub proof_size_bytes: u64,
}

impl Weight {
    /// Saturating addition — matches `Weight::saturating_add` in polkadot-sdk.
    #[inline]
    pub const fn saturating_add(self, rhs: Self) -> Self {
        Self {
            ref_time_ps: self.ref_time_ps.saturating_add(rhs.ref_time_ps),
            proof_size_bytes: self.proof_size_bytes.saturating_add(rhs.proof_size_bytes),
        }
    }
}

// --- Asset Hub Westend DbWeight (rocksdb_weights.rs) ------------------------
// RuntimeDbWeight { read: 25_000 ns, write: 100_000 ns }.
// 1 ns = 1_000 ps. RuntimeDbWeight contributes 0 to proof_size.
const DB_READ_REF_TIME_PS: u64 = 25_000 * 1_000; // 25_000_000
const DB_WRITE_REF_TIME_PS: u64 = 100_000 * 1_000; // 100_000_000

// --- Asset Hub Westend seal_get_storage (pallet_revive.rs) ------------------
// ref_time = 12_011_610 + 1_561·n + DbWeight.reads(1); proof = 252 + 1·n
const SEAL_GET_STORAGE_BASE_PS: u64 = 12_011_610;
const SEAL_GET_STORAGE_PER_BYTE_PS: u64 = 1_561;
const SEAL_GET_STORAGE_PROOF_BASE: u64 = 252;
const SEAL_GET_STORAGE_PROOF_PER_BYTE: u64 = 1;

// --- Asset Hub Westend seal_set_storage (pallet_revive.rs) ------------------
// ref_time = 13_012_834 + 423·new + 344·old + DbWeight.reads(1) + DbWeight.writes(1)
// proof = 252 + 1·old
const SEAL_SET_STORAGE_BASE_PS: u64 = 13_012_834;
const SEAL_SET_STORAGE_PER_NEW_BYTE_PS: u64 = 423;
const SEAL_SET_STORAGE_PER_OLD_BYTE_PS: u64 = 344;
const SEAL_SET_STORAGE_PROOF_BASE: u64 = 252;
const SEAL_SET_STORAGE_PROOF_PER_OLD_BYTE: u64 = 1;

// --- Asset Hub Westend clear_storage (pallet_revive.rs) ---------------------
// ref_time = 15_327_010 + 958·old + DbWeight.reads(1) + DbWeight.writes(1)
// proof = 252 + 1·old
const CLEAR_STORAGE_BASE_PS: u64 = 15_327_010;
const CLEAR_STORAGE_PER_BYTE_PS: u64 = 958;
const CLEAR_STORAGE_PROOF_BASE: u64 = 252;
const CLEAR_STORAGE_PROOF_PER_BYTE: u64 = 1;

// --- Worst-case (full - empty) overhead added by cost_storage! --------------
// get_storage_full - get_storage_empty: ref 41_765_000 - 9_436_000 = 32_329_000;
//   proof 10_663 - 653 = 10_010.
// set_storage_full - set_storage_empty: ref 43_909_000 - 10_946_000 = 32_963_000;
//   proof 10_663 - 653 = 10_010.
const READ_OVERHEAD_REF_TIME_PS: u64 = 41_765_000 - 9_436_000; // 32_329_000
const READ_OVERHEAD_PROOF: u64 = 10_663 - 653; // 10_010
const WRITE_OVERHEAD_REF_TIME_PS: u64 = 43_909_000 - 10_946_000; // 32_963_000
const WRITE_OVERHEAD_PROOF: u64 = 10_663 - 653; // 10_010

/// Closed-form base for `cost_storage!(read, seal_get_storage, _)`.
const READ_BASE_REF_TIME_PS: u64 =
    SEAL_GET_STORAGE_BASE_PS + DB_READ_REF_TIME_PS + READ_OVERHEAD_REF_TIME_PS; // 69_340_610
const READ_PROOF_BASE: u64 = SEAL_GET_STORAGE_PROOF_BASE + READ_OVERHEAD_PROOF; // 10_262

/// Closed-form base for `cost_storage!(write, seal_set_storage, _, _)`.
const WRITE_BASE_REF_TIME_PS: u64 =
    SEAL_SET_STORAGE_BASE_PS + DB_READ_REF_TIME_PS + DB_WRITE_REF_TIME_PS + WRITE_OVERHEAD_REF_TIME_PS; // 170_975_834
const WRITE_PROOF_BASE: u64 = SEAL_SET_STORAGE_PROOF_BASE + WRITE_OVERHEAD_PROOF; // 10_262

/// Closed-form base for `cost_storage!(write, clear_storage, _)`.
const CLEAR_BASE_REF_TIME_PS: u64 =
    CLEAR_STORAGE_BASE_PS + DB_READ_REF_TIME_PS + DB_WRITE_REF_TIME_PS + WRITE_OVERHEAD_REF_TIME_PS; // 173_290_010
const CLEAR_PROOF_BASE: u64 = CLEAR_STORAGE_PROOF_BASE + WRITE_OVERHEAD_PROOF; // 10_262

/// Weight of a contract storage READ of `n_bytes` (the value length returned).
///
/// Routes to `GetStorage(n)` -> `cost_storage!(read, seal_get_storage, n)`.
#[inline]
pub const fn read_weight(n_bytes: u64) -> Weight {
    Weight {
        ref_time_ps: READ_BASE_REF_TIME_PS.saturating_add(SEAL_GET_STORAGE_PER_BYTE_PS.saturating_mul(n_bytes)),
        proof_size_bytes: READ_PROOF_BASE.saturating_add(SEAL_GET_STORAGE_PROOF_PER_BYTE.saturating_mul(n_bytes)),
    }
}

/// Weight of a contract storage WRITE of `new_bytes` overwriting `old_bytes`.
///
/// Routes to `SetStorage { new_bytes, old_bytes }` ->
/// `cost_storage!(write, seal_set_storage, new_bytes, old_bytes)`.
#[inline]
pub const fn write_weight(new_bytes: u64, old_bytes: u64) -> Weight {
    Weight {
        ref_time_ps: WRITE_BASE_REF_TIME_PS
            .saturating_add(SEAL_SET_STORAGE_PER_NEW_BYTE_PS.saturating_mul(new_bytes))
            .saturating_add(SEAL_SET_STORAGE_PER_OLD_BYTE_PS.saturating_mul(old_bytes)),
        proof_size_bytes: WRITE_PROOF_BASE.saturating_add(
            SEAL_SET_STORAGE_PROOF_PER_OLD_BYTE.saturating_mul(old_bytes),
        ),
    }
}

/// Weight of a contract storage CLEAR of a previously-`old_bytes`-sized value.
///
/// Routes to `ClearStorage(old)` -> `cost_storage!(write, clear_storage, old)`.
#[inline]
pub const fn clear_weight(old_bytes: u64) -> Weight {
    Weight {
        ref_time_ps: CLEAR_BASE_REF_TIME_PS.saturating_add(CLEAR_STORAGE_PER_BYTE_PS.saturating_mul(old_bytes)),
        proof_size_bytes: CLEAR_PROOF_BASE.saturating_add(CLEAR_STORAGE_PROOF_PER_BYTE.saturating_mul(old_bytes)),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The closed forms in the module doc — locked here so a transcription typo
    /// in any constant is caught immediately.
    #[test]
    fn closed_forms_match_doc_table() {
        // read(n): 69_340_610 + 1561·n ; proof 10_262 + n
        assert_eq!(READ_BASE_REF_TIME_PS, 69_340_610);
        assert_eq!(READ_PROOF_BASE, 10_262);
        let r = read_weight(416);
        assert_eq!(r.ref_time_ps, 69_340_610 + 1_561 * 416);
        assert_eq!(r.proof_size_bytes, 10_262 + 416);

        // write(new,old): 170_975_834 + 423·new + 344·old ; proof 10_262 + old
        assert_eq!(WRITE_BASE_REF_TIME_PS, 170_975_834);
        let w = write_weight(32, 200);
        assert_eq!(w.ref_time_ps, 170_975_834 + 423 * 32 + 344 * 200);
        assert_eq!(w.proof_size_bytes, 10_262 + 200);

        // clear(old): 173_290_010 + 958·old ; proof 10_262 + old
        assert_eq!(CLEAR_BASE_REF_TIME_PS, 173_290_010);
        let c = clear_weight(416);
        assert_eq!(c.ref_time_ps, 173_290_010 + 958 * 416);
        assert_eq!(c.proof_size_bytes, 10_262 + 416);
    }

    /// A zero-byte read still costs the full per-op base (no degenerate free
    /// lunch) — this is the signal the old read-counter completely missed for
    /// distinguishing a 32-byte read from a 416-byte node read.
    #[test]
    fn per_byte_component_is_nontrivial() {
        let small = read_weight(32);
        let full_node = read_weight(416);
        // A full 416-byte node read costs exactly READ_PER_BYTE·(416−32) ps
        // MORE than a 32-byte scalar read — the delta the slot-reads-per-query
        // metric was blind to. 1_561·384 = 599_424 ps (~0.6 µs) per node.
        assert_eq!(full_node.ref_time_ps - small.ref_time_ps, SEAL_GET_STORAGE_PER_BYTE_PS * (416 - 32));
        assert!(full_node.ref_time_ps - small.ref_time_ps > 500_000);
    }

    #[test]
    fn saturating_add_is_total() {
        let a = Weight { ref_time_ps: u64::MAX - 10, proof_size_bytes: 5 };
        let b = Weight { ref_time_ps: 100, proof_size_bytes: 7 };
        let s = a.saturating_add(b);
        assert_eq!(s.ref_time_ps, u64::MAX);
        assert_eq!(s.proof_size_bytes, 12);
    }
}
