//! Tests for `#[derive(SolType)]` encoding/decoding correctness.
//!
//! These tests exercise the code generated by the `SolType` derive macro
//! against alloy's reference encoding. They were extracted from
//! `pvm-contract-types/src/tests.rs` so that derive-dependent tests live
//! in the proc-macro crate's integration test suite.

extern crate alloc;

use alloc::string::ToString;
use alloc::vec;
use alloc::vec::Vec;

use alloy_core::primitives::Address as AlloyAddress;
use alloy_core::sol_types::SolValue;
use proptest::prelude::*;
use pvm_contract_sdk::SolType;
use pvm_contract_sdk::{Address, Bytes, SolDecode, SolEncode, U256};

// ========================================================================
// Static custom struct — proptest roundtrip
// ========================================================================

#[test]
fn encode_decode_user_type_static_proptest() {
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct UserStatic {
        id: u64,
        active: bool,
    }

    proptest!(|(id: u64, active: bool)| {
        let val = UserStatic { id, active };
        let alloy = (id, active).abi_encode();
        let mut buf = vec![0u8; val.encode_len()];
        val.encode_to(&mut buf);
        prop_assert_eq!(&buf, &alloy);
        prop_assert_eq!(UserStatic::decode(&buf), val);
    });
}

// ========================================================================
// Dynamic custom struct — proptest roundtrip
// ========================================================================

#[test]
fn encode_decode_user_type_dynamic_proptest() {
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct UserDynamic {
        id: u64,
        name: alloc::string::String,
    }

    proptest!(|(id: u64, name: alloc::string::String)| {
        let val = UserDynamic { id, name };
        // Struct encode_to wraps as enc((struct)) — same as alloy's abi_encode on equivalent tuple
        let alloy = (val.id, val.name.clone()).abi_encode();
        let mut buf = vec![0u8; val.encode_len()];
        val.encode_to(&mut buf);
        prop_assert_eq!(&buf, &alloy);
        prop_assert_eq!(UserDynamic::decode(&buf), val);
    });
}

// ========================================================================
// Vec<CustomStruct> — static element type
// ========================================================================

#[test]
fn encode_decode_vector_of_user_type_static_proptest() {
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct UserStatic {
        id: u64,
        active: bool,
    }

    proptest!(|(users in proptest::collection::vec((any::<u64>(), any::<bool>()), 0..8))| {
        let val = users
            .iter()
            .copied()
            .map(|(id, active)| UserStatic { id, active })
            .collect::<Vec<_>>();
        let alloy = users.abi_encode();
        let mut buf = vec![0u8; val.encode_len()];
        val.encode_to(&mut buf);
        prop_assert_eq!(&buf, &alloy);
        prop_assert_eq!(Vec::<UserStatic>::decode(&buf), val);
    });
}

// ========================================================================
// Vec<CustomStruct> — dynamic element type
// ========================================================================

#[test]
fn encode_decode_vector_of_user_type_dynamic_proptest() {
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct UserDynamic {
        id: u64,
        name: alloc::string::String,
    }

    proptest!(|(users in proptest::collection::vec((any::<u64>(), any::<alloc::string::String>()), 0..8))| {
        let val = users
            .iter()
            .map(|(id, name)| UserDynamic {
                id: *id,
                name: name.clone(),
            })
            .collect::<Vec<_>>();
        let alloy = users.abi_encode();
        let mut buf = vec![0u8; val.encode_len()];
        val.encode_to(&mut buf);
        prop_assert_eq!(&buf, &alloy);
        prop_assert_eq!(Vec::<UserDynamic>::decode(&buf), val);
    });
}

// ========================================================================
// Nested custom types — struct containing struct
// ========================================================================

#[test]
fn encode_decode_nested_struct_proptest() {
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Point {
        x: u64,
        y: u64,
    }

    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Line {
        a: Point,
        b: Point,
    }

    proptest!(|(x1: u64, y1: u64, x2: u64, y2: u64)| {
        let val = Line {
            a: Point { x: x1, y: y1 },
            b: Point { x: x2, y: y2 },
        };
        // Nested struct encodes as nested tuple: ((uint64,uint64),(uint64,uint64))
        let alloy = ((x1, y1), (x2, y2)).abi_encode();
        let mut buf = vec![0u8; val.encode_len()];
        val.encode_to(&mut buf);
        prop_assert_eq!(&buf, &alloy);
        prop_assert_eq!(Line::decode(&buf), val);
    });
}

#[test]
fn encode_decode_triple_nested_struct() {
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Inner {
        val: u32,
    }

    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Middle {
        inner: Inner,
        extra: u64,
    }

    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Outer {
        mid: Middle,
        flag: bool,
    }

    let val = Outer {
        mid: Middle {
            inner: Inner { val: 42 },
            extra: 100,
        },
        flag: true,
    };
    // Outer = (((uint32), uint64), bool) — nested tuple encoding
    let alloy = ((42u32, 100u64), true).abi_encode();
    let mut buf = vec![0u8; val.encode_len()];
    val.encode_to(&mut buf);
    assert_eq!(&buf, &alloy);
    assert_eq!(Outer::decode(&buf), val);
}

// ========================================================================
// Dynamic struct with custom static field — the NamedPoint pattern
// ========================================================================

#[test]
fn encode_decode_dynamic_struct_with_custom_field_proptest() {
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Point {
        x: u64,
        y: u64,
    }

    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct NamedPoint {
        point: Point,
        name: alloc::string::String,
    }

    proptest!(|(x: u64, y: u64, name: alloc::string::String)| {
        let val = NamedPoint {
            point: Point { x, y },
            name: name.clone(),
        };
        // ABI: ((uint64,uint64), string) — dynamic tuple with static nested struct
        let alloy = ((x, y), name).abi_encode();
        let mut buf = vec![0u8; val.encode_len()];
        val.encode_to(&mut buf);
        // Our encoding omits the top-level tuple offset (32 bytes) that alloy prepends
        // for dynamic tuples, so compare against alloy[32..]
        prop_assert_eq!(&buf, &alloy);
        prop_assert_eq!(NamedPoint::decode(&buf), val);
    });
}

#[test]
fn encode_decode_dynamic_struct_multiple_dynamic_fields() {
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Profile {
        id: u64,
        name: alloc::string::String,
        bio: alloc::string::String,
    }

    proptest!(|(id: u64, name: alloc::string::String, bio: alloc::string::String)| {
        let val = Profile { id, name: name.clone(), bio: bio.clone() };
        let alloy = (id, name, bio).abi_encode();
        let mut buf = vec![0u8; val.encode_len()];
        val.encode_to(&mut buf);
        prop_assert_eq!(&buf, &alloy);
        prop_assert_eq!(Profile::decode(&buf), val);
    });
}

#[test]
fn encode_decode_dynamic_struct_string_then_static() {
    // String field before static field — tests offset calculation order
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Record {
        label: alloc::string::String,
        value: u64,
    }

    proptest!(|(label: alloc::string::String, value: u64)| {
        let val = Record { label: label.clone(), value };
        let alloy = (label, value).abi_encode();
        let mut buf = vec![0u8; val.encode_len()];
        val.encode_to(&mut buf);
        prop_assert_eq!(&buf, &alloy);
        prop_assert_eq!(Record::decode(&buf), val);
    });
}

// ========================================================================
// Many-field static struct — stress test offset tracking
// ========================================================================

#[test]
fn encode_decode_many_field_static_struct() {
    // Uses Address wrapper for address fields (raw [u8; 20] is now uint8[20]).
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Wide {
        a: u8,
        b: u16,
        c: u32,
        d: u64,
        e: u128,
        f: bool,
        g: Address,
    }

    proptest!(|(a: u8, b: u16, c: u32, d: u64, e: u128, f: bool, g: [u8; 20])| {
        let val = Wide {
            a, b, c, d, e, f,
          g: Address(g),
        };
        // alloy uses AlloyAddress (not our Address), so we just verify roundtrip
        let mut buf = vec![0u8; val.encode_len()];
        val.encode_to(&mut buf);
        prop_assert_eq!(Wide::decode(&buf), val);
        // Cross-validate field count: 7 fields × 32 bytes each = 224
        prop_assert_eq!(buf.len(), 7 * 32);
    });
}

// ========================================================================
// Fixed array [T; N] with custom struct elements
// ========================================================================

#[test]
fn encode_decode_fixed_array_of_struct() {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, SolType)]
    struct Point {
        x: u64,
        y: u64,
    }

    let val = [Point { x: 1, y: 2 }, Point { x: 3, y: 4 }];
    let alloy = [(1u64, 2u64), (3u64, 4u64)].abi_encode();
    let mut buf = vec![0u8; val.encode_len()];
    val.encode_to(&mut buf);
    assert_eq!(&buf, &alloy);
    assert_eq!(<[Point; 2]>::decode(&buf), val);
}

// ========================================================================
// Tuple types with custom structs
// ========================================================================

#[test]
fn encode_decode_tuple_with_struct() {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, SolType)]
    struct Point {
        x: u64,
        y: u64,
    }

    let val = (Point { x: 1, y: 2 }, 42u32);
    let alloy = ((1u64, 2u64), 42u32).abi_encode();
    let mut buf = vec![0u8; val.encode_len()];
    val.encode_to(&mut buf);
    assert_eq!(&buf, &alloy);
    assert_eq!(<(Point, u32)>::decode(&buf), val);
}

#[test]
fn encode_decode_tuple_struct_and_string() {
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Point {
        x: u64,
        y: u64,
    }

    let val = (Point { x: 7, y: 13 }, "hello world".to_string());
    let alloy = ((7u64, 13u64), "hello world".to_string()).abi_encode_params();
    let mut buf = vec![0u8; val.encode_len()];
    val.encode_to(&mut buf);
    assert_eq!(&buf, &alloy);
    assert_eq!(<(Point, alloc::string::String)>::decode(&buf), val);
}

// ========================================================================
// Dynamic fixed arrays — struct containing [String; N]
// ========================================================================

#[test]
fn encode_decode_fixed_array_of_strings() {
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct TwoNames {
        items: [alloc::string::String; 2],
    }

    let val = TwoNames {
        items: ["alpha".to_string(), "beta".to_string()],
    };
    let alloy = (["alpha".to_string(), "beta".to_string()],).abi_encode();
    let mut buf = vec![0u8; val.encode_len()];
    val.encode_to(&mut buf);
    assert_eq!(&buf, &alloy);
    assert_eq!(TwoNames::decode(&buf), val);
}

#[test]
fn encode_decode_fixed_array_of_strings_proptest() {
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct TwoNames {
        items: [alloc::string::String; 2],
    }

    proptest!(|(a: alloc::string::String, b: alloc::string::String)| {
        let val = TwoNames { items: [a.clone(), b.clone()] };
        let alloy = ([a, b],).abi_encode();
        let mut buf = vec![0u8; val.encode_len()];
        val.encode_to(&mut buf);
        prop_assert_eq!(&buf, &alloy);
        prop_assert_eq!(TwoNames::decode(&buf), val);
    });
}

// ========================================================================
// Dynamic struct containing [Struct; N] (the "Polygon" pattern)
// ========================================================================

#[test]
fn encode_decode_dynamic_struct_with_fixed_array_of_structs() {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, SolType)]
    struct Point {
        x: u64,
        y: u64,
    }

    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Polygon {
        vertices: [Point; 3],
        name: alloc::string::String,
    }

    let val = Polygon {
        vertices: [
            Point { x: 1, y: 2 },
            Point { x: 3, y: 4 },
            Point { x: 5, y: 6 },
        ],
        name: "triangle".to_string(),
    };
    let alloy = (
        [(1u64, 2u64), (3u64, 4u64), (5u64, 6u64)],
        "triangle".to_string(),
    )
        .abi_encode();
    let mut buf = vec![0u8; val.encode_len()];
    val.encode_to(&mut buf);
    assert_eq!(&buf, &alloy);
    assert_eq!(Polygon::decode(&buf), val);
}

// ========================================================================
// Vec<Struct> with nested custom types
// ========================================================================

#[test]
fn encode_decode_vec_of_nested_struct_proptest() {
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Point {
        x: u64,
        y: u64,
    }

    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Line {
        a: Point,
        b: Point,
    }

    proptest!(|(lines in proptest::collection::vec(
        (any::<u64>(), any::<u64>(), any::<u64>(), any::<u64>()),
        0..4
    ))| {
        let val: Vec<Line> = lines
            .iter()
            .map(|&(x1, y1, x2, y2)| Line {
                a: Point { x: x1, y: y1 },
                b: Point { x: x2, y: y2 },
            })
            .collect();
        let alloy_tuples: Vec<((u64, u64), (u64, u64))> = lines
            .iter()
            .map(|&(x1, y1, x2, y2)| ((x1, y1), (x2, y2)))
            .collect();
        let alloy = alloy_tuples.abi_encode();
        let mut buf = vec![0u8; val.encode_len()];
        val.encode_to(&mut buf);
        prop_assert_eq!(&buf, &alloy);
        prop_assert_eq!(Vec::<Line>::decode(&buf), val);
    });
}

// ========================================================================
// SOL_NAME tests for custom types
// ========================================================================

#[test]
fn sol_type_name_custom_structs() {
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Point {
        x: u64,
        y: u64,
    }

    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Line {
        a: Point,
        b: Point,
    }

    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct NamedPoint {
        point: Point,
        name: alloc::string::String,
    }

    assert_eq!(<Point as SolEncode>::SOL_NAME, "(uint64,uint64)");
    assert_eq!(
        <Line as SolEncode>::SOL_NAME,
        "((uint64,uint64),(uint64,uint64))"
    );
    assert_eq!(
        <NamedPoint as SolEncode>::SOL_NAME,
        "((uint64,uint64),string)"
    );
}

#[test]
fn vec_sol_name_for_custom_struct() {
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Point {
        x: u64,
        y: u64,
    }

    assert_eq!(<Vec<Point> as SolEncode>::SOL_NAME, "(uint64,uint64)[]");
}

// ========================================================================
// Empty Vec<Struct> edge case
// ========================================================================

#[test]
fn encode_decode_empty_vec_of_struct() {
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Point {
        x: u64,
        y: u64,
    }

    let val: Vec<Point> = vec![];
    let alloy_val: Vec<(u64, u64)> = vec![];
    let alloy = alloy_val.abi_encode();
    let mut buf = vec![0u8; val.encode_len()];
    val.encode_to(&mut buf);
    assert_eq!(&buf, &alloy);
    assert_eq!(Vec::<Point>::decode(&buf), val);
}

// ========================================================================
// Struct with Vec field (dynamic struct containing a dynamic collection)
// ========================================================================

#[test]
fn encode_decode_struct_with_vec_field() {
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct TokenList {
        owner: Address,
        amounts: Vec<U256>,
    }

    let val = TokenList {
        owner: Address([0xAB; 20]),
        amounts: vec![U256::from(100u64), U256::from(200u64)],
    };
    let alloy = (
        AlloyAddress::from([0xAB; 20]),
        vec![U256::from(100u64), U256::from(200u64)],
    )
        .abi_encode();
    let mut buf = vec![0u8; val.encode_len()];
    val.encode_to(&mut buf);
    assert_eq!(&buf, &alloy);
    assert_eq!(TokenList::decode(&buf), val);
}

#[test]
fn encode_decode_struct_with_vec_and_string() {
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Record {
        id: u64,
        tags: Vec<alloc::string::String>,
        note: alloc::string::String,
    }

    let val = Record {
        id: 42,
        tags: vec!["a".to_string(), "bb".to_string()],
        note: "hello".to_string(),
    };
    let alloy = (
        42u64,
        vec!["a".to_string(), "bb".to_string()],
        "hello".to_string(),
    )
        .abi_encode();
    let mut buf = vec![0u8; val.encode_len()];
    val.encode_to(&mut buf);
    assert_eq!(&buf, &alloy);
    assert_eq!(Record::decode(&buf), val);
}

// ========================================================================
// IS_DYNAMIC flag tests for custom structs
// ========================================================================

#[test]
fn is_dynamic_flag_correct_for_custom_structs() {
    // Custom structs (static)
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct StaticPair {
        x: u64,
        y: u64,
    }
    const { assert!(!<StaticPair as SolEncode>::IS_DYNAMIC) };

    // Custom structs (dynamic)
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct DynamicRecord {
        id: u64,
        name: alloc::string::String,
    }
    const { assert!(<DynamicRecord as SolEncode>::IS_DYNAMIC) };

    // Nested static struct
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct NestedStatic {
        pair: StaticPair,
        flag: bool,
    }
    const { assert!(!<NestedStatic as SolEncode>::IS_DYNAMIC) };

    // Nested struct with dynamic inner
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct NestedDynamic {
        record: DynamicRecord,
        count: u64,
    }
    const { assert!(<NestedDynamic as SolEncode>::IS_DYNAMIC) };
}

// ========================================================================
// Bytes in struct
// ========================================================================

#[test]
fn encode_decode_struct_with_bytes_field() {
    #[derive(Debug, PartialEq, SolType)]
    struct WithBytes {
        id: u64,
        data: Bytes,
    }

    let val = WithBytes {
        id: 42,
        data: Bytes(vec![0xDE, 0xAD, 0xBE, 0xEF]),
    };
    let mut buf = vec![0u8; val.encode_len()];
    val.encode_to(&mut buf);
    assert_eq!(WithBytes::decode(&buf), val);
}

#[test]
fn encode_decode_struct_with_empty_bytes() {
    #[derive(Debug, PartialEq, SolType)]
    struct WithEmptyBytes {
        id: u64,
        data: Bytes,
    }

    let val = WithEmptyBytes {
        id: 0,
        data: Bytes(vec![]),
    };
    let mut buf = vec![0u8; val.encode_len()];
    val.encode_to(&mut buf);
    assert_eq!(WithEmptyBytes::decode(&buf), val);
}

// ========================================================================
// encode_to — smart top-level ABI encoding for structs
// ========================================================================

#[test]
fn encode_to_dynamic_struct() {
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Profile {
        id: u64,
        name: alloc::string::String,
    }

    let val = Profile {
        id: 42,
        name: "alice".to_string(),
    };
    let alloy = ((42u64, "alice".to_string()),).abi_encode_params();
    let mut buf = vec![0u8; val.encode_len()];
    val.encode_to(&mut buf);
    assert_eq!(&buf, &alloy);
}

#[test]
fn encode_to_static_struct() {
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Point {
        x: u64,
        y: u64,
    }

    let val = Point { x: 1, y: 2 };
    let alloy = ((1u64, 2u64),).abi_encode_params();
    let mut buf = vec![0u8; val.encode_len()];
    val.encode_to(&mut buf);
    assert_eq!(&buf, &alloy);
}

// ========================================================================
// Return value encoding — verified against alloy sol! function signatures
// ========================================================================

use alloy_core::sol_types::SolCall;

alloy_core::sol! {
    function getStaticStruct() external view returns (uint64, uint64);
    function getDynamicStruct() external view returns (uint64, string);

    // Struct as single return — wraps with offset
    struct SolProfile {
        uint64 id;
        string name;
    }
    function getProfile() external view returns (SolProfile);

    // Nested struct in multi-return
    struct SolPoint {
        uint64 x;
        uint64 y;
    }
    function getPointAndName() external view returns (SolPoint, string);

    // Nested: struct containing dynamic field as single return
    struct SolRecord {
        uint64 id;
        string name;
        bool active;
    }
    function getRecord() external view returns (SolRecord);
}

#[test]
fn return_encoding_static_struct() {
    // function getStaticStruct() returns (uint64, uint64)
    // This is multi-return with 2 static values — same as a static struct
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Point {
        x: u64,
        y: u64,
    }

    // As multi-return (tuple)
    let our_tuple = {
        let val = (1u64, 2u64);
        let mut buf = vec![0u8; val.encode_len()];
        val.encode_to(&mut buf);
        buf
    };
    // As single struct return
    let our_struct = {
        let val = Point { x: 1, y: 2 };
        let mut buf = vec![0u8; val.encode_len()];
        val.encode_to(&mut buf);
        buf
    };
    let alloy = getStaticStructCall::abi_encode_returns(&getStaticStructReturn { _0: 1, _1: 2 });
    // Multi-return tuple matches alloy
    assert_eq!(our_tuple, alloy);
    // Static struct also matches (no offset for static types)
    assert_eq!(our_struct, alloy);
}

#[test]
fn return_encoding_dynamic_struct() {
    // function getDynamicStruct() returns (uint64, string)
    // As multi-return: tuple with IS_TUPLE=true → flat body
    // As single struct return: IS_TUPLE=false → offset-wrapped
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Profile {
        id: u64,
        name: alloc::string::String,
    }

    let our_tuple = {
        let val = (42u64, "alice".to_string());
        let mut buf = vec![0u8; val.encode_len()];
        val.encode_to(&mut buf);
        buf
    };
    let alloy = getDynamicStructCall::abi_encode_returns(&getDynamicStructReturn {
        _0: 42,
        _1: "alice".to_string(),
    });
    // Multi-return tuple matches alloy's return encoding
    assert_eq!(our_tuple, alloy);

    // Single struct return is DIFFERENT — has outer offset wrapper
    let our_struct = {
        let val = Profile {
            id: 42,
            name: "alice".to_string(),
        };
        let mut buf = vec![0u8; val.encode_len()];
        val.encode_to(&mut buf);
        buf
    };
    // Struct wraps: [offset=32][body], which is 32 bytes longer
    assert_eq!(our_struct.len(), alloy.len() + 32);
    // The body after the offset matches the multi-return encoding
    assert_eq!(&our_struct[32..], &alloy);
}

#[test]
fn return_encoding_single_dynamic_struct() {
    // returns (SolProfile) — single struct return, gets offset wrapper
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Profile {
        id: u64,
        name: alloc::string::String,
    }

    let val = Profile {
        id: 42,
        name: "alice".to_string(),
    };
    let our = {
        let mut buf = vec![0u8; val.encode_len()];
        val.encode_to(&mut buf);
        buf
    };
    let alloy = getProfileCall::abi_encode_returns(&SolProfile {
        id: 42,
        name: "alice".to_string(),
    });
    assert_eq!(our, alloy);
}

#[test]
fn return_encoding_struct_in_multi_return() {
    // returns (SolPoint, string) — static struct + dynamic string as multi-return
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Point {
        x: u64,
        y: u64,
    }

    // The macro flattens multi-return — but here the struct is one field
    // In Solidity, SolPoint is a tuple (uint64, uint64) inlined in the return
    let val = (Point { x: 1, y: 2 }, "label".to_string());
    let our = {
        let mut buf = vec![0u8; val.encode_len()];
        val.encode_to(&mut buf);
        buf
    };
    let alloy = getPointAndNameCall::abi_encode_returns(&getPointAndNameReturn {
        _0: SolPoint { x: 1, y: 2 },
        _1: "label".to_string(),
    });
    assert_eq!(our, alloy);
}

#[test]
fn return_encoding_complex_struct() {
    // returns (SolRecord) — struct with 3 fields (static, dynamic, static) as single return
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Record {
        id: u64,
        name: alloc::string::String,
        active: bool,
    }

    let val = Record {
        id: 1,
        name: "test".to_string(),
        active: true,
    };
    let our = {
        let mut buf = vec![0u8; val.encode_len()];
        val.encode_to(&mut buf);
        buf
    };
    let alloy = getRecordCall::abi_encode_returns(&SolRecord {
        id: 1,
        name: "test".to_string(),
        active: true,
    });
    assert_eq!(our, alloy);
}

#[test]
fn return_encoding_roundtrip_advanced() {
    // decode(encode_to(val)) == val for all advanced types
    #[derive(Clone, Debug, PartialEq, Eq, SolType)]
    struct Profile {
        id: u64,
        name: alloc::string::String,
    }

    let p = Profile {
        id: 7,
        name: "bob".to_string(),
    };
    let mut buf = vec![0u8; p.encode_len()];
    p.encode_to(&mut buf);
    assert_eq!(Profile::decode(&buf), p);

    let t = (true, "x".to_string(), 9u64);
    let mut buf = vec![0u8; t.encode_len()];
    t.encode_to(&mut buf);
    assert_eq!(<(bool, alloc::string::String, u64)>::decode(&buf), t);

    let nested = ((1u64, 2u64), "z".to_string());
    let mut buf = vec![0u8; nested.encode_len()];
    nested.encode_to(&mut buf);
    assert_eq!(<((u64, u64), alloc::string::String)>::decode(&buf), nested);
}
