// Turns the emitted `fixtures/abi/*.abi.json` files into a TypeScript module of
// `as const satisfies Abi` literals.
//
// This exists for the type-inference half of the suite. A JSON import — even
// with `resolveJsonModule` — widens to `string` and `unknown[]`, so abitype has
// nothing to infer from and `encodeFunctionData` degrades to accepting any
// `functionName`. Only a literal with `as const` in the source lets us assert
// that a user importing our ABI gets real autocomplete and real argument types.
//
// `satisfies Abi` rather than `as Abi`: the former checks the literal against
// viem's ABI type *without* widening it, so a malformed emitted ABI fails
// `pnpm typecheck` instead of being silently coerced.
//
// The output is checked in, and CI fails on any diff, so this is also the point
// where an ABI shape change becomes visible in review.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const abiDir = join(here, '..', 'fixtures', 'abi')
const outFile = join(here, '..', 'src', 'generated', 'abis.ts')

/** `multi-method` -> `multiMethodAbi` */
function exportName(stem) {
  const camel = stem.replace(/[-_.]+(.)/g, (_, c) => c.toUpperCase())
  return `${camel}Abi`
}

// Sorted so the generated file is stable regardless of directory-read order —
// otherwise the CI drift gate would flap.
const files = readdirSync(abiDir)
  .filter((f) => f.endsWith('.abi.json'))
  .sort()

if (files.length === 0) {
  throw new Error(
    `No ABI fixtures in ${abiDir}. Run: cargo run -p pvm-viem-roundtrip --bin gen-viem-fixtures`,
  )
}

const chunks = [
  '// GENERATED by scripts/gen-abi-ts.mjs — do not edit.',
  '//',
  '// Source: fixtures/abi/*.abi.json, emitted by',
  '// `cargo run -p pvm-viem-roundtrip --bin gen-viem-fixtures`.',
  '',
  "import type { Abi } from 'viem'",
  '',
]

const names = []

for (const file of files) {
  const stem = file.replace(/\.abi\.json$/, '')
  const raw = JSON.parse(readFileSync(join(abiDir, file), 'utf8'))
  // Contracts with declared storage emit `{"abi": [...], "storageLayout": {...}}`
  // instead of a bare array. `storageLayout` is a solc-ism viem never reads, so
  // only the ABI half is carried through.
  const abi = Array.isArray(raw) ? raw : raw.abi
  if (!Array.isArray(abi)) {
    throw new Error(`${file}: expected an ABI array or an object with an "abi" key`)
  }

  const name = exportName(stem)
  names.push([stem, name])
  chunks.push(
    `export const ${name} = ${JSON.stringify(abi, null, 2)} as const satisfies Abi`,
    '',
  )
}

// A name -> ABI lookup, so the runtime suites can walk every ABI generically
// while the individual exports stay literally typed for the type tests.
chunks.push(
  'export const abis = {',
  ...names.map(([stem, name]) => `  ${JSON.stringify(stem)}: ${name},`),
  '} as const',
  '',
  'export type AbiName = keyof typeof abis',
  '',
)

writeFileSync(outFile, chunks.join('\n'))
console.error(`Wrote ${names.length} ABIs to ${outFile}`)
