[package]
name = "pvm-contract"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Runtime library for PVM smart contracts"

[dependencies]
pvm-contract-macros = { path = "../pvm-contract-macros" }
ruint = { version = "1.17", default-features = false }
pallet-revive-uapi = { version = "0.9", default-features = false }
polkavm-derive.workspace = true
