[workspace]

[package]
name = "new-from-sol-fibonacci-alloc"
version = "0.1.0"
edition = "2024"
rust-version = "1.92"
build = "build.rs"

[[bin]]
name = "new-from-sol-fibonacci-alloc"
path = "src/fibonacci.rs"

[dependencies]
pvm-contract-macros = { path = "../../crates/pvm-contract-macros" }
pvm-contract-types = { path = "../../crates/pvm-contract-types" }
pallet-revive-uapi = { version = "0.9", default-features = false }
polkavm-derive = { version = "0.31.0" }
ruint = { version = "1.17", default-features = false }
picoalloc = { version = "5", default-features = false }


[build-dependencies]
cargo-pvm-contract-builder = { path = "../../crates/cargo-pvm-contract-builder" }


[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
overflow-checks = false